### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@the-turk

**Comment by the-turk** [comment]
Thank you! But.. that supposed to be a "heading text". What makes you think that this is a wrong capitalization?

**Comment by Justman10000** [comment]
> Thank you! But.. that supposed to be a "heading text". What makes you think that this is a wrong capitalization?

In English this is irrelevant! Always the first word in upper case, the rest in lower case. The well-known rule, learned in first grade, if not earlier

**Comment by the-turk** [comment]
have you ever heard of "title case" ??

**Comment by Justman10000** [comment]
> have you ever heard of "title case" ??

?

**Comment by Justman10000** [comment]
@the-turk

**Pull request closed without merging**
